"""Toy IT-helpdesk corpus, a background corpus for the dense model, and labeled queries.

Queries come in two types:
  * keyword    : exact rare tokens (error codes, product names, flags) that a lexical model should nail
  * paraphrase : the same need phrased with different words (little or no term overlap with the doc)
Relevance is graded: 2 = the answer doc, 1 = related/partially useful.
"""

DOCS = {
    "d01": "Resetting your password: open the account portal, choose forgot password, and a reset link is emailed that expires after 30 minutes.",
    "d02": "Error ERR-4012 means the SSO token has expired. Sign out, clear the browser cookies and sign in again to get a fresh token.",
    "d03": "The VPN client WireGate drops the tunnel when the laptop sleeps. Enable the keepalive option in WireGate settings to keep the connection alive.",
    "d04": "To add a network printer, open printer settings, click add device and enter the queue name such as PRN-3F-EAST.",
    "d05": "Invoices are generated on the first day of each month. Download past invoices as PDF from the billing page.",
    "d06": "Refunds for annual plans are prorated. Contact the billing team within 14 days of renewal to request money back.",
    "d07": "The public API allows 600 requests per minute per key. Requests over the limit receive HTTP 429 and should retry with exponential backoff.",
    "d08": "Nightly backups run at 02:00 UTC and are kept for 35 days. Restore a file from the backup console by picking a snapshot date.",
    "d09": "Multi-factor authentication can use an authenticator app or a hardware key. Lost your phone? Use one of the recovery codes.",
    "d10": "Laptop battery draining fast? Lower screen brightness, close background apps and switch the power mode to battery saver.",
    "d11": "Shared mailbox access is granted by your manager in the directory. After approval the mailbox appears in the mail client within an hour.",
    "d12": "Disk quota on the home drive is 50 GB. When the quota is full, delete old files or request more storage from IT.",
    "d13": "Kernel panic with code KP-0x7E on boot usually points to a faulty RAM module. Run the memory diagnostic and replace the failing stick.",
    "d14": "The flag --dry-run on the deploy tool prints the planned changes without applying them to production.",
    "d15": "Conference room displays use the CastLink dongle. Press the button on the dongle to mirror your screen to the room TV.",
    "d16": "Wi-Fi keeps disconnecting? Forget the network, reconnect to CorpNet-5G, and make sure the wireless driver is up to date.",
    "d17": "New employees receive a laptop on day one. Onboarding covers account setup, security training and installing core apps.",
    "d18": "To uninstall software on a managed laptop, open the Company Portal, find the app and select remove.",
    "d19": "Phishing emails often fake urgency. Do not click links; report suspicious messages with the report phish button.",
    "d20": "Timesheets must be submitted every Friday by 17:00 in the HR portal. Late submissions delay payroll.",
    "d21": "The build server Jenkins-7 runs unit tests on every pull request. A red build blocks merging until tests pass.",
    "d22": "Large files over 2 GB should be shared with the FileDrop service rather than attached to email.",
    "d23": "Monitor flickering is usually a loose cable. Reseat the DisplayPort cable or try a different port on the dock.",
    "d24": "Keyboard shortcuts: press Win+L to lock your screen whenever you leave your desk.",
    "d25": "Database connection error PG-53300 means too many connections. Close idle sessions or raise the connection pool limit.",
    "d26": "Expense reports need receipts attached. Travel costs are reimbursed within ten business days after approval.",
    "d27": "Software licenses for the design suite are assigned per seat. Ask your team lead to request an extra seat.",
    "d28": "Headset microphone not working in calls? Select the headset as the input device and check the mute switch on the cable.",
    "d29": "Encrypt USB drives with the built-in drive encryption before storing customer data on removable media.",
    "d30": "Parking permits for the office garage are renewed each January through the facilities portal.",
}

# Background text used ONLY to fit the dense (LSA) projection, playing the role of an embedding model's
# pre-training data. It links synonyms by co-occurrence; it is never indexed or retrieved.
BACKGROUND = [
    "forgot password reset credentials login sign in recover access account locked",
    "cannot log in sign in credentials passphrase password recover account access",
    "vpn tunnel remote connection connect from home secure network drops disconnects",
    "working from home remote access vpn tunnel disconnects keeps dropping connection",
    "printer print printing paper queue device add install printer",
    "invoice bill billing statement receipt payment charge monthly",
    "refund money back reimburse cancel plan billing charge return",
    "api requests per minute rate limit throttled throttling too many requests 429",
    "backup restore recover deleted file snapshot copy lost file",
    "accidentally deleted file recover restore backup snapshot",
    "authenticator two factor multi factor mfa 2fa second factor verification code phone",
    "battery power drain charge lasts longer laptop battery saver",
    "mailbox shared inbox email mail team inbox access",
    "storage space quota disk full drive space capacity home drive",
    "ram memory module stick crash boot blue screen panic",
    "dry run preview planned changes without applying simulate deploy",
    "screen mirror cast share screen tv display projector meeting room",
    "wifi wireless internet network disconnects drops connection",
    "new hire new employee onboarding first day starter joining",
    "uninstall remove delete app software program",
    "phishing scam suspicious email fake link fraud report",
    "timesheet hours worked submit weekly payroll salary paid",
    "build ci tests pull request merge pipeline failing red",
    "large file big file share send transfer attachment too big",
    "monitor screen display flicker flickering cable blinking",
    "lock screen lock computer leave desk shortcut",
    "database connections too many sessions pool limit",
    "expense reimburse reimbursement travel costs receipts paid back",
    "license seat software access design tool extra seat",
    "headset microphone mic audio input calls cannot hear me",
    "usb stick removable drive encrypt encryption thumb drive",
    "parking car garage permit office",
    "laptop computer notebook machine device",
    "sign in log in login authenticate",
    "token session expired sso single sign on",
]

# (id, type, query, {doc: grade})
QUERIES = [
    ("q01", "keyword", "ERR-4012", {"d02": 2}),
    ("q02", "keyword", "WireGate keepalive", {"d03": 2}),
    ("q03", "keyword", "PRN-3F-EAST queue", {"d04": 2}),
    ("q04", "keyword", "HTTP 429 exponential backoff", {"d07": 2}),
    ("q05", "keyword", "KP-0x7E kernel panic", {"d13": 2}),
    ("q06", "keyword", "--dry-run deploy tool", {"d14": 2}),
    ("q07", "keyword", "CastLink dongle", {"d15": 2}),
    ("q08", "keyword", "CorpNet-5G", {"d16": 2}),
    ("q09", "keyword", "Jenkins-7 pull request", {"d21": 2}),
    ("q10", "keyword", "PG-53300 connections", {"d25": 2}),
    ("q11", "keyword", "FileDrop 2 GB", {"d22": 2}),
    ("q12", "keyword", "Win+L", {"d24": 2}),
    ("q13", "paraphrase", "I can't remember my login credentials", {"d01": 2, "d09": 1}),
    ("q14", "paraphrase", "how do I get my money back after cancelling", {"d06": 2, "d05": 1}),
    ("q15", "paraphrase", "remote connection from home keeps dropping", {"d03": 2, "d16": 1}),
    ("q16", "paraphrase", "I accidentally deleted a document, can it be recovered", {"d08": 2}),
    ("q17", "paraphrase", "we are being throttled for too many calls", {"d07": 2}),
    ("q18", "paraphrase", "my notebook doesn't last long unplugged", {"d10": 2}),
    ("q19", "paraphrase", "no space left on my drive", {"d12": 2}),
    ("q20", "paraphrase", "show my laptop on the meeting room tv", {"d15": 2, "d23": 1}),
    ("q21", "paraphrase", "people on the call cannot hear me", {"d28": 2}),
    ("q22", "paraphrase", "a starter joins next week, what happens on the first day", {"d17": 2}),
    ("q23", "paraphrase", "get paid back for travel costs", {"d26": 2, "d06": 1}),
    ("q24", "paraphrase", "screen keeps blinking", {"d23": 2}),
    ("q25", "paraphrase", "suspicious message asking me to click a link", {"d19": 2}),
    ("q26", "paraphrase", "preview changes without touching prod", {"d14": 2}),
    ("q27", "paraphrase", "second factor code when my phone is lost", {"d09": 2}),
    ("q28", "paraphrase", "protect a thumb drive holding client data", {"d29": 2}),
]
